language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "gradle build -x test"

# CI 실행 완료시 메일로 알람
notifications:
  slack: codesquad-members:spCVtRGv1cIYYRI66pFvBfTl


before_deploy:
  - zip -r springboot-overdiary *
  - mkdir -p deploy
  - mv springboot-overdiary.zip deploy/springboot-overdiary.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-overdiary-deploy-bucket # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: ksm0814/overDiary #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-overdiary-deploy-bucket # S3 버킷
    key: springboot-overdiary.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot-overdiary # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-overdiary-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: ksm0814/overDiary
      branch: master